image: python:3-slim-stretch
stages:
  - deploy

build and push:
  stage: deploy
  before_script:
     - apt-get update -qq && apt-get install -y -qq wget curl
  script:
     - pip install awscli
     - pip install --require-hashes --no-cache-dir -r requirements.txt    
     - ./bin/mirror.sh
     - aws s3 sync ./_site ${STAGE_BUCKET_PATH} --acl public-read --delete
     - aws s3 sync ./_site ${PROD_BUCKET_PATH} --acl public-read --delete
     - curl ${DMS}

