sudo: required
services:
  - docker
language: python
env:
  global:
    # NewRelic
    - NEWRELIC_STAGE_APPLICATION=careers-stage-us-west
    - NEWRELIC_PROD_APPLICATION=careers-prod-us-west
    # Deis
    - DEIS_STAGE_APPLICATION=careers-stage
    - DEIS_PROD_APPLICATION=careers-stage
    - DEIS_USERNAME=travis
    - DEIS_CONTROLLER=https://deis.us-west.moz.works
    # Docker
    - DOCKER_REPOSITORY=mozorg/lumbergh
    - DOCKER_EMAIL="foo@example.com"
    - DOCKER_USERNAME="mozjenkins"
    # Django
    - DEBUG=False
    - ALLOWED_HOSTS=*
    - SECRET_KEY=foo
    - DATABASE_URL=postgres://postgres@db/postgres
install:
  - docker pull ${DOCKER_REPOSITORY}:last_successful_build || true
  - docker pull ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} || true
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
before_script:
  - env > .env
script:
  - docker run -d --name pgsql postgres:9.4
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} flake8 careers
  # Give time to pgsql to initialize.
  - sleep 5s;
  - docker run --env-file .env --link pgsql:db ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} ./manage.py test
deploy:
  - provider: script
    script: bin/deploy-travis.sh $DEIS_STAGE_APPLICATION $NEWRELIC_STAGE_APPLICATION
    on:
      branch: master
      repo: mozilla/lumbergh
  - provider: script
    script: bin/deploy-travis.sh $DEIS_PROD_APPLICATION $NEWRELIC_PROD_APPLICATION
    on:
      tags: true
      repo: mozilla/lumbergh
