sudo: required
services:
  - docker
language: python
env:
  global:
    # Docker
    - DOCKER_REPOSITORY=mozorg/lumbergh

    # Django
    - DEBUG=False
    - ALLOWED_HOSTS=*
    - SECRET_KEY=foo
    - DATABASE_URL=sqlite://
    - SECURE_SSL_REDIRECT=False
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  # Take advantage of docker caching by pulling previously built images.
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
before_script:
  # Replace all spaces with _
  - env | sed 's/ /_/' > .env
script:
  - docker run ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} flake8 careers
  # Wait database to initialize.
  - docker run --env-file .env ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} coverage run ./manage.py test
